export const SERVICES = [
  { icon: 'Code2', title: 'Web Development', description: 'Full-stack apps and marketing sites built for scale, from React frontends to Postgres-backed APIs.' },
  { icon: 'Smartphone', title: 'Mobile Apps', description: 'Native iOS/Android and cross-platform apps shipped to the store, not just a Figma file.' },
  { icon: 'Monitor', title: 'Desktop Software', description: 'Cross-platform desktop tools for internal ops, engineering, and regulated environments.' },
  { icon: 'Workflow', title: 'DevOps', description: 'CI/CD, container orchestration, infrastructure-as-code — deploys measured in minutes.' },
  { icon: 'ShieldCheck', title: 'Cybersecurity', description: 'Threat modeling, hardening, and secure-by-default architecture for teams that can’t afford a breach.' },
  { icon: 'Cpu', title: 'AI / ML Solutions', description: 'Applied ML — recommendation, forecasting, and LLM-backed workflows shipped to production.' },
  { icon: 'Zap', title: 'Automation', description: 'Replace manual ops with resilient pipelines: data sync, reporting, internal tooling.' },
  { icon: 'PenTool', title: 'UI/UX Design', description: 'Interfaces designed for the people who’ll use them daily, not just the demo.' },
  { icon: 'Compass', title: 'Project Consulting', description: 'Technical due diligence, architecture review, and roadmap planning for leadership teams.' },
];

export const PROCESS = [
  { title: 'Discover', description: 'Scope, constraints, and success metrics — a short technical audit, not a sales deck.' },
  { title: 'Architect', description: 'System design, risk register, and a delivery plan your team can review line by line.' },
  { title: 'Build', description: 'Iterative delivery in weekly increments, visible in a staging environment from week one.' },
  { title: 'Ship', description: 'Production rollout with a rollback plan, monitoring, and a runbook your team keeps.' },
  { title: 'Support', description: 'On-call coverage and a maintenance retainer, or a clean handoff — your call.' },
];

export const VALUES = [
  { title: 'One accountable team', description: 'No handoffs between strangers. The engineers who scope your project are the ones who ship it.' },
  { title: 'Documented by default', description: 'Architecture decisions, runbooks, and API contracts are written down — not tribal knowledge.' },
  { title: 'Built for handoff', description: 'Every engagement ends with your team able to run the system without us, whether or not you keep us on retainer.' },
];

// Real, shipped work. Keep this list honest — no placeholder metrics or
// invented client names. Add entries here as engagements are completed.
// `hidden: true` keeps an entry's data in place (and its detail page
// un-generated, so the URL 404s) without deleting it — use this to pull a
// case study from the public site temporarily.
const ALL_CASE_STUDIES = [
  {
    slug: 'sadjia-ceram',
    tag: 'Retail · Web',
    category: 'Web',
    title: 'SADJIA CERAM — digital showroom',
    summary: 'A digital product catalog and real-time price estimator for a ceramic tile retailer in Oran, replacing phone-quoted pricing with self-serve browsing and quoting.',
    stack: ['HTML/CSS/JS', 'Admin dashboard', 'DZD pricing engine'],
    metric: 'Catalog + estimator + admin, one build',
    challenge: 'Customers had no way to browse SADJIA CERAM’s tile collections or estimate a project’s cost without calling the showroom — every quote required a phone call or a visit in person.',
    approach: 'We built a self-serve digital showroom: a catalog filterable by dimension and type, a real-time price estimator in Algerian dinar keyed to surface area, and an admin dashboard so the showroom team manages products and pricing without touching code.',
    result: 'A live catalog and quoting tool customers use before ever calling the showroom, plus a management dashboard the team runs day to day.',
  },
  {
    slug: 'logistics-dashboard',
    tag: 'Logistics · Desktop',
    category: 'Desktop',
    title: 'Logistics & distribution management dashboard',
    summary: 'A desktop and web dashboard for tracking transportation and distribution operations, packaged as a native app alongside a Supabase-backed web deployment.',
    stack: ['Electron', 'Vite + TypeScript', 'Supabase'],
    metric: 'Desktop + web from one codebase',
    challenge: 'A transportation and distribution operation needed one system to track fleet, deliveries, and the financial side of the business — deployable both as an installed desktop tool and a hosted web app.',
    approach: 'We built the dashboard once in Vite and TypeScript and shipped it two ways: an Electron desktop build for local/offline use, and a Supabase-backed web deployment — same codebase, same data layer.',
    result: 'A single dashboard covering distribution operations and financials, packaged for both desktop installs and web access.',
  },
  {
    slug: 'ability-beyond-disability',
    tag: 'Social impact · Web',
    category: 'Web',
    title: 'Ability Beyond Disability',
    summary: 'A bilingual (Arabic/English) landing page showcasing the talents and achievements of people with disabilities across Algeria.',
    stack: ['HTML/CSS', 'Bilingual (AR/EN)'],
    metric: 'Nationwide talent showcase',
    challenge: 'People with disabilities across Algeria needed a public platform to showcase their creative and professional work — one that reads as a polished showcase, not a charity page.',
    approach: 'We designed a visually engaging, accessible static site: a talent gallery, stats on registered talents and provinces represented, and event/workshop promotion — built to load fast with no backend dependency.',
    result: 'A live, accessible showcase site highlighting talent from across Algeria’s provinces.',
  },
  {
    slug: 'little-hafiz',
    tag: 'EdTech · Mobile',
    category: 'Mobile',
    title: 'Little Hafiz — Quran memorization app',
    summary: 'A Flutter Quran memorization app for kids and adults, with verse-by-verse listening, progress tracking, and an installable offline-capable web build.',
    stack: ['Flutter', 'PWA / offline-capable', 'Cross-platform'],
    metric: 'Web, iOS & Android from one codebase',
    challenge: 'Quran memorization apps are common, but few are built for kids specifically, with progress parents can actually follow.',
    approach: 'We built one Flutter codebase spanning verse-by-verse listening, multiple memorization methods, and progress tracking, shipped as an installable, offline-capable Progressive Web App with mobile builds from the same source.',
    result: 'A cross-platform memorization app installable straight from the browser, no app-store gatekeeping required.',
  },
  {
    slug: 'sahafood',
    tag: 'Foodtech · Mobile',
    category: 'Mobile',
    title: 'SahaFood — food delivery app',
    summary: 'A Flutter food delivery app covering the customer-facing ordering flow. Currently in active development.',
    stack: ['Flutter', 'Mobile'],
    metric: 'In active development',
    challenge: 'Food delivery in the target market runs through phone orders and third-party apps that take a cut of every sale — SahaFood needed its own ordering channel.',
    approach: 'We’re building the customer-facing Flutter app first — browsing, ordering, checkout — with the merchant and delivery-side systems to follow.',
    result: 'The ordering app is in active development. This entry will update as it ships.',
  },
  {
    slug: 'id-verification-pipeline',
    tag: 'Computer vision · AI/ML',
    category: 'AI/ML',
    title: 'ID card detection & segmentation pipeline',
    summary: 'A computer-vision pipeline that detects, segments, and perspective-corrects Algerian ID cards from a phone camera frame, producing an OCR-ready crop.',
    stack: ['YOLOv8', 'ONNX / TFLite', 'Python + Flutter'],
    metric: 'Camera frame → OCR-ready crop, on-device',
    challenge: 'Reading an ID card reliably from a phone photo means handling rotation, partial framing, and inconsistent lighting before OCR ever runs.',
    approach: 'We trained a YOLOv8 segmentation model on the MIDV-500 dataset to find and mask the card, paired with a lightweight oriented-bounding-box detector for mobile framing, exporting both to ONNX and TFLite for on-device inference.',
    result: 'A camera-to-crop pipeline — detect, segment, perspective-warp — ready to feed any OCR engine, running on-device on mobile.',
  },
  {
    slug: 'tradevirtual',
    tag: 'Fintech · Web',
    category: 'Web',
    title: 'TradeVirtual — crypto paper-trading platform',
    summary: 'A gamified platform for practicing cryptocurrency trading with simulated funds — live prices, XP and leaderboards, no real money at risk.',
    stack: ['Next.js', 'TypeScript', 'Prisma'],
    metric: '6 tracked assets · live pricing',
    challenge: 'New traders want to learn how crypto trading actually feels without risking real money — and most paper-trading tools feel like spreadsheets, not products.',
    approach: 'We built a full trading simulator on Next.js and Prisma: live prices pulled from Binance every few seconds, a real buy/sell flow with trade history, and a gamification layer — XP, levels, a global leaderboard — to keep it engaging.',
    result: 'A live simulated-trading platform with real-time pricing and a competitive leaderboard, not just a static demo.',
  },
  {
    slug: 'thodz-builder',
    tag: 'SaaS · Web',
    category: 'Web',
    title: 'THODZ Builder — no-code portfolio builder',
    summary: 'A drag-and-drop website builder that lets anyone assemble a professional portfolio site from customizable templates, no code required.',
    stack: ['Next.js', 'Prisma + Postgres', 'Supabase'],
    metric: '5 templates · drag-and-drop editor',
    challenge: 'Freelancers who need a portfolio site rarely want to (or can) hand-code one, and most builders are either too generic or too locked-down to customize.',
    approach: 'We built a drag-and-drop editor on Next.js — reorder sections, swap between five distinct template styles from minimal to dark-mode developer aesthetics — backed by a Supabase/Prisma account system.',
    result: 'A working no-code builder covering template selection, drag-and-drop editing, and sign-up/account flows end to end.',
  },
  {
    slug: 'chronic-disease-monitoring',
    tag: 'Healthtech · Web',
    category: 'Web',
    title: 'Chronic disease monitoring platform',
    summary: 'A role-based web app where patients log health measurements and receive AI-drafted, doctor-reviewed treatment guidance.',
    stack: ['Firebase Auth', 'Firebase Realtime Database', 'JavaScript'],
    metric: 'Patient + doctor roles · doctor-approved output',
    challenge: 'Patients managing a chronic condition need a simple way to log measurements and get guidance — but AI-generated medical suggestions are only trustworthy with a clinician in the loop.',
    approach: 'We built two roles into one system: patients submit measurements and get an AI-drafted report, and a doctor account reviews, edits, and approves every report and prescription before the patient ever sees it.',
    result: 'A working patient/doctor monitoring loop — submission, AI drafting, clinical review — with full history tracking on both sides.',
  },
  {
    slug: 'boonka',
    hidden: true,
    tag: 'Fintech · Payments',
    category: 'Web',
    title: 'Boonka — payment gateway platform',
    summary: 'Product design and website for a digital payment platform serving Algerian e-commerce, spanning personal, business, and partner-facing applications.',
    stack: ['Next.js', 'Payments', 'Multilingual (FR/EN/AR)'],
    metric: '3 applications · 1 platform',
    challenge: 'Boonka needed a trust-first digital identity for a market where buyers and merchants are wary of online payment: online shoppers who don’t fully trust paying before delivery, and merchants who need to get paid without arbitrary delays.',
    approach: 'We designed the product experience and marketing site around a single idea — payment protection — and built it to speak to two audiences from one entry point: a personal wallet app for shoppers, and a business app for merchants, each with its own dedicated flows, before converging on shared trust signals (secured funds, real-time transaction visibility).',
    result: 'A coherent, multilingual (French / English / Arabic) product and website spanning all three Boonka applications — individual, business, and partner — ready for the platform’s public launch.',
  },
];

export const CASE_STUDIES = ALL_CASE_STUDIES.filter((c) => !c.hidden);
export const CASE_STUDIES_ALL = ALL_CASE_STUDIES;
